CREATE TYPE "ROLE" AS ENUM (
  'VIEWER',
  'CREATOR'
);

CREATE TYPE "EVENT" AS ENUM (
  'VIEW',
  'REACT',
  'COMMENT',
  'SHARE'
);

CREATE TABLE "user" (
  "id" uuid PRIMARY KEY,
  "name" string NOT NULL,
  "avatar" string,
  "role" ROLE NOT NULL DEFAULT 'VIEWER',
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "video" (
  "id" uuid PRIMARY KEY,
  "title" string NOT NULL,
  "desc" text,
  "category_id" int NOT NULL,
  "score" int DEFAULT 0,
  "creator_id" uuid NOT NULL,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "event" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "type" EVENT
);

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "video" ("creator_id");

ALTER TABLE "category" ADD FOREIGN KEY ("id") REFERENCES "video" ("category_id");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "event" ("user_id");

ALTER TABLE "video" ADD FOREIGN KEY ("id") REFERENCES "event" ("video_id");
