CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "user" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "name" VARCHAR NOT NULL,
  "avatar" VARCHAR,
  "role" VARCHAR NOT NULL DEFAULT 'VIEWER',
  "updated_at" TIMESTAMP DEFAULT now(),
  "created_at" TIMESTAMP DEFAULT now(),
  CHECK ("role" IN ('VIEWER', 'CREATOR'))
);


CREATE TABLE IF NOT EXISTS "video" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "title" varchar NOT NULL,
  "desc" text,
  "category_id" int NOT NULL,
  "creator_id" uuid NOT NULL,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "event" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "type" varchar,
  "payload" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  CHECK ("type" IN ('COMMENT', 'REACT', 'SHARE', 'VIEW'))
);

ALTER TABLE "video" ADD FOREIGN KEY ("creator_id") REFERENCES "user" ("id");

ALTER TABLE "video" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");

ALTER TABLE "event" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "event" ADD FOREIGN KEY ("video_id") REFERENCES "video" ("id");



-- Dummy data
INSERT INTO "user" ("id","name", "role") VALUES
  ('057e6539-733b-47f9-a034-b72a2c00c291','user1', 'CREATOR'),
  ('09976c26-5d9b-499e-93f9-0dbaadea7dbd','user2', 'VIEWER'),
  ('4b81bf9a-cc01-471b-bda0-46318cf74d55','user3', 'VIEWER'),
  ('6cf86cc2-4dde-4650-a17f-b3b8535e8776','user4', 'VIEWER'),
  ('b68206bc-59fa-4a4d-8d34-648dc52f8039','user5', 'VIEWER'),
  ('da6074ff-95a1-4961-82c1-55a2a40995a8','user6', 'VIEWER');

INSERT INTO "category" ("name") VALUES
  ('Thể thao'),
  ('Giải trí');

INSERT INTO "video" ("title", "desc", "category_id", "creator_id") VALUES
  ('Video 1', 'Mô tả video 1', 1, '057e6539-733b-47f9-a034-b72a2c00c291'),
  ('Video 2', 'Mô tả video 2', 1, '057e6539-733b-47f9-a034-b72a2c00c291'),
  ('Video 3', 'Mô tả video 3', 1, '057e6539-733b-47f9-a034-b72a2c00c291'),
  ('Video 4', 'Mô tả video 4', 2, '057e6539-733b-47f9-a034-b72a2c00c291'),
  ('Video 5', 'Mô tả video 5', 2, '057e6539-733b-47f9-a034-b72a2c00c291'),
  ('Video 6', 'Mô tả video 6', 2, '057e6539-733b-47f9-a034-b72a2c00c291');


